### ISSUE TITLE
expose cpuTime on compositor + mainframe events?

### ISSUE THREAD

**Issue by igrigorik** [googlearchive/frame-timing-polyfill#17]
> nduca@: the reason for cpuTime is because fps can't go faster than 60 typically [its device specific, and many devices actually dont support turning off vsync]. The discrete nature of fps means its a good smoke signal but very bad measure for catching slow creep regressions. If an onscroll or raf suddenly goes up by 2x but was 2ms to begin with, or worse someone adds css that increases raster time, or someone checks in splashscreen.jpeg in highres form, then you wont see those costs yet it'll affect smoothness. I wanted that to be reflected somehow in the api.
> 
> There's one final thing I want to bring up: descheduled events. For those not familiar with systrace or similar, give it a try... http://developer.android.com/tools/debugging/systrace.html. These tools show that when you use highres time, you're measuring "wall time" separate from "cpu time." When the kernel deschedules your thread for another thread, wall time keeps advancing. CPU time, on the other hand (clock_gettime with CLOCK_THREAD_CPUTIME_ID) stops advancing when your'e descheduled.
> 
> It turns out that you get much higher quality numbers when you use the cpu time. Hence why I said cpuTime in this. But maybe what we should be doing is figuring out how to get the performance timeline to include highResCpuTime .

Current proposal defines `cpuTime` on `PerformanceMainFrameTiming` but omits it on `PerformanceCompositeTiming`, with thinking that cpuTime is the total across all threads.

Instead, should we expose `cpuTime` on both events? That would make the interface more consistent and provides a more granular view into where the cpuTime is spent. New definition would be something like: 
- _"The cpuTime attribute must return a [High Resolution Time] duration giving the total CPU time of the associated thread."_

**Comment by natduca** [comment]
We shouldn't specify what threads a browser runs composite and mainFrame on. Its important that they're separate to compute compositor-to-main-frame skew. But, when it comes to talking about "cost", we must specify this as a global cost independent of threads.

Compositor draw events are instantaneous and just indicated that we did draw [or began composited drawing]. If they were heavy their cost should attribute themselves back to the main frame for which they are associated.

**Comment by igrigorik** [comment]
Moved to https://github.com/w3c/smoothness/issues/1
