### ISSUE TITLE
Move FPSMeter to be client of RangeMontior

### ISSUE THREAD

**Issue by natduca** [googlearchive/frame-timing-polyfill#4]
<a href="https://github.com/natduca"><img src="https://avatars.githubusercontent.com/u/412396?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [natduca](https://github.com/natduca)**
_Fri Aug 22 21:33:31 2014_
_Originally opened as https://github.com/mpb/webfps/issues/13_

---

**Comment by natduca** [comment]
<a href="https://github.com/natduca"><img src="https://avatars.githubusercontent.com/u/412396?v=2" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [natduca](https://github.com/natduca)**
_Mon Sep  8 19:17:45 2014_

---

This bug stands. FPSmeter should not be using collector.

**Comment by mpb** [comment]
FPS meter doesn't show great data now, need to look into this some more.
