### ISSUE TITLE
Move FPSMeter element into iframe so it doesn't cause endless drawing

### ISSUE THREAD

**Issue by natduca** [googlearchive/frame-timing-polyfill#5]
<a href="https://github.com/natduca"><img src="https://avatars.githubusercontent.com/u/412396?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [natduca](https://github.com/natduca)**
_Fri Aug 22 21:33:58 2014_
_Originally opened as https://github.com/mpb/webfps/issues/14_

---

**Comment by natduca** [comment]
<a href="https://github.com/mpb"><img src="https://avatars.githubusercontent.com/u/8249221?v=2" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mpb](https://github.com/mpb)**
_Tue Sep  2 20:58:07 2014_

---

I moved it into an iframe, but it still triggers "composite" events on the main frame. We probably need to run through either a tracefile or gdb to see why CC decided that the main frame/layer should get an event when the meter is updated.

**Comment by natduca** [comment]
<a href="https://github.com/mpb"><img src="https://avatars.githubusercontent.com/u/8249221?v=2" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mpb](https://github.com/mpb)**
_Mon Sep  8 17:51:06 2014_

---

I moved the main body of the page into an iframe that doesn't overlap the FPS meter as well, and same story. It seems that Blink or CC decided that something on the screen changed, so it asked for all the layers that made up the screen, and called drawLayers on them. The way my patch is plugged in, this is interpreted as being drawn. (I suppose in a way it is, but we were hoping to show that we can register 0 events when there are 0 changes being drawn)

**Comment by natduca** [comment]
<a href="https://github.com/natduca"><img src="https://avatars.githubusercontent.com/u/412396?v=2" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [natduca](https://github.com/natduca)**
_Mon Sep  8 19:21:51 2014_

---

To clarify, we know this is a bug in our implementation of the monitoring api, not a bug in how iframes/perf timeline works. If we fix our bug in the c++ side of things, then this new approach should work.

**Comment by mpb** [comment]
Fixed in https://codereview.chromium.org/397443002
