### ISSUE TITLE
SmoothnessInfoForRange.*events shoul be private

### ISSUE THREAD

**Issue by natduca** [googlearchive/frame-timing-polyfill#8]
<a href="https://github.com/natduca"><img src="https://avatars.githubusercontent.com/u/412396?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [natduca](https://github.com/natduca)**
_Mon Sep  8 20:14:41 2014_
_Originally opened as https://github.com/mpb/webfps/issues/24_

---

Should just have monitor track a SmoothnessInfoForRange, then have SmoothnessInfoForRange.addInfo(otherSmoothnessInfo) that internally combines the events. The fact that SIFR has events should be hidden.

**Comment by mpb** [comment]
The reason it made them public was so the fps monitor could have sub-1-second resolution. For that to happen, it needs more than just the average # of draws over a time period, it needs more like a stream of time deltas. What would be a reasonable way to expose that?
